# ShapeModelisation Module
Ce  module permet de récupérer une forme géométrique dans un espace 2D dans une matrice de nombre optimisée.

## Notes

On itère sur les lignes et les colonnes si celle-ci sont rempli de 0 on les supprime   
On réduit ainsi les bornes et le nombre de variables

In [1]:
from __future__ import print_function
import time 
import mahotas
import numpy as np 
from operator import itemgetter

In [2]:
# Différentes formes géométriques dans l'espace 2D
#[X, Y] coordinates

shape1 = [(3, 2), (3, 8), (8, 8), (8, 3), (7, 2)]
shape2 = [(1, 2), (3, 5), (6, 7), (9, 7), (11, 6), (10, 3), (8, 2)]

canvas = np.zeros((13,13))
mahotas.polygon.fill_polygon([(1, 2), (3, 5), (6, 7), (9, 7), (11, 6), (10, 3), (8, 2)], canvas)
print(canvas)
#mahotas.polygon.fill_polygon([(3, 2), (3, 8), (8, 8), (8, 3), (7, 2)], canvas)


# On parcours les lignes
row_indices = []
for i, row in enumerate(canvas):
    # Vérifie qu'une ligne est au moins un 1
    if np.all(row == 0):
        row_indices.append(i)

# On parcours les colonnes
col_indices = []
for i, col in enumerate(canvas.T):
    if np.all(col == 0):
        col_indices.append(i)

# Redimension du tableau
canvas = np.delete(canvas, row_indices, axis = 0)
canvas = np.delete(canvas, col_indices, axis = 1)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
# Ce que l'on a. 
# On a une liste de coordonées.

# Ce que l'on veut.
# Un tableau de variables prêtes à l'emploi

class ShapeModeler():
    """
    This class allow us to model a polygon in 2D dimension with ndarray.
    """
    def __init__(self,list_coordinates):
        self.list_coordinates = list_coordinates
        dim = self.max_dimension()
        self.canvas = np.zeros(dim)

    def draw_shape_canvas(self):
        """ Alterate the canvas that represents the 2D space
        Args: None

        Returns: None
        """
        # Il faudra checker plus tard si est ce que notre forme est bien un polygon
        mahotas.polygon.fill_polygon(self.list_coordinates, self.canvas)

    def max_list_tuple(self, sequence):
        """Find the maximum value in list of tuples
        Args: sequence: list of tuples
        Returns: maximum value (int)
        """
        if not sequence:
            raise ValueError('empty sequence') 

        maximum = sequence[0][0] 
        max_local = maximum
        for item in sequence:
            if item[0] > item[1]:
                max_local = item[0]
            else:
                max_local = item[1]

            if max_local > maximum:
                maximum = max_local

        return maximum

    def max_dimension(self):
        """Return a tuple that contains the maximum limits of 2D space
        Args: None
        Returns: 2D dimensions limits (tuple)(int,int)
        """
        max = self.max_list_tuple(self.list_coordinates)
        return (max + 1, max + 1)

    def shrink_space(self):
        """
        Reducing the 2D space ndarray in order to reduce the number of 
        computational variable
        Args: None
        Returns: None
        """
        # On parcours les lignes
        row_indices = []
        for i, row in enumerate(self.canvas):
        # Vérifie qu'une ligne est au moins un 1
            if np.all(row == 0):
                row_indices.append(i)

        # On parcours les colonnes
        col_indices = []
        for i, col in enumerate(self.canvas.T):
            if np.all(col == 0):
                col_indices.append(i)

        # Redimension du tableau
        self.canvas = np.delete(self.canvas, row_indices, axis = 0)
        self.canvas = np.delete(self.canvas, col_indices, axis = 1)

    def get_canvas(self):
        """
        Args: None
        Returns: 2D space canvas (ndarray)
        """
        return self.canvas

In [44]:
sh = ShapeModeler(shape2)
sh.draw_shape_canvas()
sh.shrink_space()
res = sh.get_canvas()
print(res)

[[1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0.]]
